const items = [
  {
    name: "Digestive Biscuits",
    price: 2.99,
    category: "Biscuits",

  },
  {
    name: "Chocolate Chip Cookies",
    price: 3.49,
    category: "Biscuits",
  },
  {
    name: "Cream Sandwich Biscuits",
    price: 1.99,
    category: "Biscuits",
  },
  {
    name: "Oatmeal Raisin Cookies",
    price: 2.79,
    category: "Biscuits",
  },
  {
    name: "Shortbread Biscuits",
    price: 2.49,
    category: "Biscuits",
  },
  {
    name: "Coconut Macaroons",
    price: 2.99,
    category: "Biscuits",
  },
  { name: "Butter Cookies", price: 3.29, category: "Biscuits" },
  { name: "Wafer Biscuits", price: 1.99, category: "Biscuits" },
  { name: "Almond Biscotti", price: 3.99, category: "Biscuits" },
  {
    name: "Gingerbread Cookies",
    price: 2.49,
    category: "Biscuits",
  },
  {
    name: "Snickerdoodle Cookies",
    price: 2.79,
    category: "Biscuits",
  },
  {
    name: "Salted Caramel Biscuits",
    price: 3.99,
    category: "Biscuits",
  },
  { name: "Cheese Crackers", price: 2.29, category: "Biscuits" },
  {
    name: "Peanut Butter Cookies",
    price: 2.99,
    category: "Biscuits",
  },
  {
    name: "Custard Cream Biscuits",
    price: 1.99,
    category: "Biscuits",
  },

  { name: "Cola", price: 1.99, category: "Beverages" },
  { name: "Orange Juice", price: 2.49, category: "Beverages" },
  { name: "Mineral Water", price: 0.99, category: "Beverages" },
  { name: "Lemonade", price: 1.49, category: "Beverages" },
  { name: "Iced Tea", price: 1.79, category: "Beverages" },
  { name: "Coffee", price: 2.99, category: "Beverages" },
  { name: "Hot Chocolate", price: 2.79, category: "Beverages" },
  { name: "Milkshake", price: 3.99, category: "Beverages" },
  { name: "Smoothie", price: 3.49, category: "Beverages" },
  { name: "Green Tea", price: 1.99, category: "Beverages" },
  { name: "Apple Cider", price: 2.99, category: "Beverages" },
  { name: "Soda Water", price: 0.79, category: "Beverages" },

  { name: "Ballpoint Pen", price: 1.99, category: "Stationary" },
  { name: "Notebook", price: 2.49, category: "Stationary" },
  {
    name: "Highlighter Set",
    price: 4.99,
    category: "Stationary",
  },
  { name: "Sticky Notes", price: 1.49, category: "Stationary" },
  { name: "Pencil Case", price: 3.99, category: "Stationary" },
  { name: "Scissors", price: 2.79, category: "Stationary" },
  { name: "Calculator", price: 5.99, category: "Stationary" },
  { name: "Eraser", price: 0.99, category: "Stationary" },
  { name: "Ruler", price: 1.49, category: "Stationary" },
  { name: "Binder Clips", price: 2.29, category: "Stationary" },
  { name: "Markers", price: 3.99, category: "Stationary" },
  { name: "Stapler", price: 4.49, category: "Stationary" },
  {
    name: "Correction Tape",
    price: 1.79,
    category: "Stationary",
  },

  { name: "Olive Oil", price: 9.99, category: "Edible Oils" },
  { name: "Coconut Oil", price: 6.49, category: "Edible Oils" },
  {
    name: "Sunflower Oil",
    price: 4.99,
    category: "Edible Oils",
  },
  { name: "Canola Oil", price: 5.49, category: "Edible Oils" },
  { name: "Sesame Oil", price: 7.99, category: "Edible Oils" },
  { name: "Peanut Oil", price: 5.99, category: "Edible Oils" },
  { name: "Corn Oil", price: 4.79, category: "Edible Oils" },
  { name: "Soybean Oil", price: 4.49, category: "Edible Oils" },
  {
    name: "Grapeseed Oil",
    price: 6.99,
    category: "Edible Oils",
  },
  { name: "Avocado Oil", price: 8.49, category: "Edible Oils" },
  {
    name: "Rice Bran Oil",
    price: 4.99,
    category: "Edible Oils",
  },
  { name: "Mustard Oil", price: 3.99, category: "Edible Oils" },

  { name: "Apple", price: 1.99, category: "Fruits" },
  { name: "Banana", price: 0.49, category: "Fruits" },
  { name: "Orange", price: 0.79, category: "Fruits" },
  { name: "Strawberry", price: 2.99, category: "Fruits" },
  { name: "Grapes", price: 3.99, category: "Fruits" },
  { name: "Watermelon", price: 4.99, category: "Fruits" },
  { name: "Pineapple", price: 2.49, category: "Fruits" },
  { name: "Mango", price: 1.99, category: "Fruits" },
  { name: "Kiwi", price: 1.79, category: "Fruits" },
  { name: "Blueberries", price: 3.49, category: "Fruits" },
  { name: "Peach", price: 1.99, category: "Fruits" },
  { name: "Pear", price: 1.49, category: "Fruits" },

  { name: "Carrot", price: 0.99, category: "Vegetables" },
  { name: "Broccoli", price: 1.49, category: "Vegetables" },
  { name: "Tomato", price: 0.79, category: "Vegetables" },
  { name: "Spinach", price: 1.29, category: "Vegetables" },
  { name: "Cucumber", price: 0.99, category: "Vegetables" },
  { name: "Bell Pepper", price: 1.49, category: "Vegetables" },
  { name: "Onion", price: 0.69, category: "Vegetables" },
  { name: "Potato", price: 0.89, category: "Vegetables" },
  { name: "Zucchini", price: 1.29, category: "Vegetables" },
  { name: "Cauliflower", price: 1.99, category: "Vegetables" },
  { name: "Lettuce", price: 1.79, category: "Vegetables" },
  { name: "Eggplant", price: 1.39, category: "Vegetables" },

  { name: "Turmeric Powder", price: 2.99, category: "Masalas" },
  { name: "Cumin Seeds", price: 1.49, category: "Masalas" },
  { name: "Coriander Powder", price: 2.49, category: "Masalas" },
  { name: "Red Chili Powder", price: 1.99, category: "Masalas" },
  { name: "Garam Masala", price: 3.49, category: "Masalas" },
  { name: "Mustard Seeds", price: 1.29, category: "Masalas" },
  { name: "Fenugreek Seeds", price: 1.79, category: "Masalas" },
  { name: "Cinnamon Powder", price: 2.29, category: "Masalas" },
  { name: "Cardamom Pods", price: 3.99, category: "Masalas" },
  { name: "Cloves", price: 2.79, category: "Masalas" },
  { name: "Fennel Seeds", price: 1.99, category: "Masalas" },
  { name: "Black Pepper", price: 2.49, category: "Masalas" },

  { name: "Basmati Rice", price: 9.99, category: "Rice" },
  { name: "Jasmine Rice", price: 8.49, category: "Rice" },
  { name: "Brown Rice", price: 6.99, category: "Rice" },
  { name: "Sushi Rice", price: 7.99, category: "Rice" },
  { name: "Arborio Rice", price: 10.49, category: "Rice" },
  { name: "Wild Rice", price: 12.99, category: "Rice" },
  { name: "Red Rice", price: 8.99, category: "Rice" },
  { name: "Parboiled Rice", price: 6.49, category: "Rice" },
  { name: "Black Rice", price: 11.99, category: "Rice" },
  { name: "Sticky Rice", price: 7.49, category: "Rice" },
  { name: "Biryani Rice", price: 9.49, category: "Rice" },
  { name: "Forbidden Rice", price: 13.99, category: "Rice" },

  {
    name: "Refrigerator",
    price: 999.99,
    category: "Home Appliances",
  },
  {
    name: "Washing Machine",
    price: 799.99,
    category: "Home Appliances",
  },
  {
    name: "Microwave Oven",
    price: 199.99,
    category: "Home Appliances",
  },
  {
    name: "Air Conditioner",
    price: 1299.99,
    category: "Home Appliances",
  },
  {
    name: "Television",
    price: 699.99,
    category: "Home Appliances",
  },
  {
    name: "Vacuum Cleaner",
    price: 149.99,
    category: "Home Appliances",
  },
  { name: "Toaster", price: 39.99, category: "Home Appliances" },
  {
    name: "Coffee Maker",
    price: 79.99,
    category: "Home Appliances",
  },
  { name: "Blender", price: 69.99, category: "Home Appliances" },
  {
    name: "Electric Kettle",
    price: 49.99,
    category: "Home Appliances",
  },
  {
    name: "Hair Dryer",
    price: 29.99,
    category: "Home Appliances",
  },
  { name: "Iron", price: 49.99, category: "Home Appliances" },

  {
    name: "Milk Chocolate",
    price: 1.99,
    category: "Chocolates",
  },
  {
    name: "Dark Chocolate",
    price: 2.49,
    category: "Chocolates",
  },
  {
    name: "White Chocolate",
    price: 2.99,
    category: "Chocolates",
  },
  {
    name: "Caramel Chocolate",
    price: 2.99,
    category: "Chocolates",
  },
  {
    name: "Hazelnut Chocolate",
    price: 3.49,
    category: "Chocolates",
  },
  {
    name: "Almond Chocolate",
    price: 2.99,
    category: "Chocolates",
  },
  {
    name: "Mint Chocolate",
    price: 2.49,
    category: "Chocolates",
  },
  {
    name: "Fruit & Nut Chocolate",
    price: 2.99,
    category: "Chocolates",
  },
  {
    name: "Cookies & Cream Chocolate",
    price: 2.99,
    category: "Chocolates",
  },
  {
    name: "Coconut Chocolate",
    price: 2.99,
    category: "Chocolates",
  },
  {
    name: "Raspberry Chocolate",
    price: 2.99,
    category: "Chocolates",
  },
  {
    name: "Orange Chocolate",
    price: 2.49,
    category: "Chocolates",
  },

  {
    name: "Potato Chips",
    price: 1.99,
    category: "Snacks",
  },
  { name: "Pretzels", price: 1.49, category: "Snacks" },
  { name: "Popcorn", price: 2.49, category: "Snacks" },
  { name: "Cheese Puffs", price: 1.99, category: "Snacks" },
  { name: "Mixed Nuts", price: 3.99, category: "Snacks" },
  { name: "Trail Mix", price: 2.99, category: "Snacks" },
  { name: "Crackers", price: 1.79, category: "Snacks" },
  { name: "Granola Bars", price: 2.99, category: "Snacks" },
  { name: "Pita Chips", price: 1.99, category: "Snacks" },
  { name: "Rice Cakes", price: 1.49, category: "Snacks" },
  { name: "Tortilla Chips", price: 2.49, category: "Snacks" },
  { name: "Sesame Sticks", price: 1.99, category: "Snacks" },

  { name: "Milk", price: 2.99, category: "Dairy Products" },
  { name: "Cheese", price: 4.99, category: "Dairy Products" },
  { name: "Yogurt", price: 1.99, category: "Dairy Products" },
  { name: "Butter", price: 3.49, category: "Dairy Products" },
  { name: "Cream", price: 2.99, category: "Dairy Products" },
  {
    name: "Cottage Cheese",
    price: 3.99,
    category: "Dairy Products",
  },
  {
    name: "Sour Cream",
    price: 1.99,
    category: "Dairy Products",
  },
  {
    name: "Greek Yogurt",
    price: 2.49,
    category: "Dairy Products",
  },
  {
    name: "Mozzarella Cheese",
    price: 4.49,
    category: "Dairy Products",
  },
  {
    name: "Whipped Cream",
    price: 2.99,
    category: "Dairy Products",
  },
  {
    name: "Ricotta Cheese",
    price: 3.99,
    category: "Dairy Products",
  },
  {
    name: "Cream Cheese",
    price: 3.49,
    category: "Dairy Products",
  },

  {
    name: "Frozen Pizza",
    price: 4.99,
    category: "Frozen Foods",
  },
  {
    name: "Frozen Vegetables",
    price: 2.49,
    category: "Frozen Foods",
  },
  { name: "Ice Cream", price: 3.99, category: "Frozen Foods" },
  {
    name: "Frozen Burgers",
    price: 5.99,
    category: "Frozen Foods",
  },
  { name: "Frozen Fish", price: 6.99, category: "Frozen Foods" },
  {
    name: "Frozen Chicken Nuggets",
    price: 3.99,
    category: "Frozen Foods",
  },
  {
    name: "Frozen Fries",
    price: 2.99,
    category: "Frozen Foods",
  },
  {
    name: "Frozen Fruit",
    price: 4.49,
    category: "Frozen Foods",
  },
  {
    name: "Frozen Desserts",
    price: 3.99,
    category: "Frozen Foods",
  },
  { name: "Frozen Pies", price: 4.99, category: "Frozen Foods" },
  {
    name: "Frozen Breakfast Sandwiches",
    price: 3.49,
    category: "Frozen Foods",
  },
  {
    name: "Frozen Dinners",
    price: 4.99,
    category: "Frozen Foods",
  },
];

export default items;
